### ISSUE TITLE
大神有没有遇到过我这种情况，求解

### ISSUE THREAD

**Issue by lil-nail** [zlxbuzz/parcel-demo#8]
×  Cannot read property 'add' of undefined
    at JSPackager.addAsset (D:\parcel\node_modules\parcel-bundler\src\packagers\JSPackager.js:55:32)
    at Bundle._addDeps (D:\parcel\node_modules\parcel-bundler\src\Bundle.js:208:20)
    at <anonymous>

**Comment by zlxbuzz** [comment]
@bug-hky 这个应该是你的`parcel`版本比较新的问题，这个例子还是`1.2.0`的版本，比较老，所以推荐clone下来后通过yarn来安装

**Comment by lil-nail** [comment]
@zlxbuzz 好的，万分感谢
